[package]
name = "gm-power"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
gm-core.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Memory",
    "Win32_System_Power",
    "Win32_System_Registry",
    "Win32_System_ProcessStatus",
    "Win32_System_Services",
    "Win32_System_SystemInformation",
    "Win32_System_Threading",
] }
